### ISSUE TITLE
Implement Landing Page

### ISSUE THREAD

**Issue by empeje** [chingu-voyage3/toucans-28#2]
Here is our mock-up for the landing page.

https://wireframepro.mockflow.com/view/D2154e08bbbb37a36e4513cd63ff14e7b#/page/D966c55218586d0aeaf72e1a8825250b5

And this is the todos:
- [ ] Skeleton/Structure + Navigation @devkonyan (#4)
- [ ] Carousel for quote or other stuff (#5)
- [ ] About @empeje  (#6)
- [ ] Portofolio @debu2code  (#7)
- [ ] Footer (#8)

Put your comment and the task you want to take.

Please help to choose technology.
- JS
- HTML5
- CSS
- Bootstrap?

![mockup](https://user-images.githubusercontent.com/11813607/33527098-5e8c0076-d87d-11e7-8e9c-c32f94a60cee.png)

**Comment by iamdebajyotibanerjee** [comment]
I'll do the portfolio section.

**Comment by ghost** [comment]
i will make project structure
